### ISSUE TITLE
Fix out-dated step number

### ISSUE THREAD

**Issue by hg-pyun** [es-shims/Array.prototype.toSorted#3]
The steps noted in the comments in [the implementation.js](https://github.com/es-shims/Array.prototype.toSorted/blob/main/implementation.js) file of the Array.prototype.toSorted repository do not match the numbering in [the specification document](https://tc39.es/proposal-change-array-by-copy/#sec-array.prototype.toSorted).

To re-number the steps from 5 to 9 in the implementation.js file and appropriately merge the missing numbers, you will need to adjust the comments in the code to reflect the new numbering.

**Comment by ljharb** [comment]
Indeed, thanks.
